[project]
name = "gen-botpic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "pillow>=11.2.1",
    "pyinstaller>=6.14.1",
    "pytest>=8.4.0",
]
